- hosts: deploy_instance
  gather_facts: no
  tasks:
  - name: Clone a github repository
    git:
      repo: https://github.com/daticahealth/java-tomcat-maven-example.git
      dest: java-tomcat-maven-example/
      clone: yes
      update: yes
  - name: copy Dockerfile
    ansible.builtin.copy:
      src: ./Dockerfile
      dest: java-tomcat-maven-example/Dockerfile
  - name: Build container image
    community.docker.docker_image_build:
      name: ghcr.io/permeenev/java-tomcat-maven-example:0.2
      path: java-tomcat-maven-example
      dockerfile: Dockerfile