- hosts: deploy_instance
  gather_facts: no
  tasks:
  - name: Clone a github repository
    git:
      repo: https://github.com/daticahealth/java-tomcat-maven-example.git
      dest: java-tomcat-maven-example/
      clone: yes
      update: yes
  - name: copy Dockerfile
    ansible.builtin.copy:
      src: ./Dockerfile
      dest: java-tomcat-maven-example/Dockerfile
  - name: build container image
    docker_image:
      name: "ghcr.io/permeenev/java-tomcat-maven-example:0.2"
      build:
        path: /var/lib/jenkins/workspace/ansible2/java-tomcat-maven-example/Dockerfile
        source: build
      state: present