- hosts: prod_instance
  gather_facts: no
  tasks:
    - name: 'Docker pull'
      community.docker.docker_image:
        name: ghcr.io/permeenev/java-tomcat-maven-example:0.5
        source: pull
    - name: 'Container present'
      community.docker.docker_container:
        name: 'java-tomcat-maven-example-0.5'
        state: present
        image: ghcr.io/permeenev/java-tomcat-maven-example:0.5