- hosts: prod_instance
  gather_facts: no
  tasks:
    - name: 'Docker pull'
      community.docker.docker_image:
        name: ghcr.io/permeenev/java-tomcat-maven-example:{{ version }}
        source: pull
    - name: Log into private docker registry 
      community.docker.docker_login:
        registry_url: ghcr.io
        username: permeenev
        password: '{{ key_storage }}'
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info
    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    - name: 'Container start'
      community.docker.docker_container:
        name: 'java-tomcat-maven-example-{{ version }}'
        image: ghcr.io/permeenev/java-tomcat-maven-example:{{ version }}
        state: started
        restart: true
        ports:
        # Publish container port 8080 as host port 8080
        - "8080:8080"