- hosts: deploy_instance
  gather_facts: no
  tasks:
  - name: Clone a github repository
    git:
      repo: https://github.com/daticahealth/java-tomcat-maven-example.git
      dest: java-tomcat-maven-example/
      clone: yes
      update: yes
  - name: copy Dockerfile
    ansible.builtin.copy:
      src: ./Dockerfile
      dest: java-tomcat-maven-example/Dockerfile
  - name: Change the working directory to somedir/ before executing the command
    ansible.builtin.shell: |
      docker build -t ghcr.io/permeenev/java-tomcat-maven-example:0.2 .
      echo $9a2e8890-86ed-43b7-ab47-51ce79c70587 | docker login ghcr.io -u permeenev --password-stdin
      docker push ghcr.io/permeenev/java-tomcat-maven-example:0.2
    args:
      chdir: java-tomcat-maven-example/